// Dictionary data
var dictionary = [
// Dictionary data
var dictionary = [
{ english: "Abstraction", indonesia: "Abstraksi" },
    { english: "Access Control", indonesia: "Kontrol Akses" },
    { english: "Activation Function", indonesia: "Fungsi Aktivasi" },
    { english: "Active Learning", indonesia: "Pembelajaran Aktif" },
    { english: "Adversarial Attack", indonesia: "Serangan Adversarial" },
    { english: "Agile Development", indonesia: "Pengembangan Agile" },
    { english: "AI Ethics", indonesia: "Etika Kecerdasan Buatan (AI)" },
    { english: "Algorithmic Bias", indonesia: "Bias Algoritmik" },
    { english: "Algorithmic Trading", indonesia: "Perdagangan Algoritmik" },
    { english: "Anomaly Detection", indonesia: "Deteksi Anomali" },
    { english: "API (Application Programming Interface)", indonesia: "Antarmuka Pemrograman Aplikasi" },
    { english: "AR (Augmented Reality)", indonesia: "Realitas Tertambah" },
    { english: "Artificial General Intelligence (AGI)", indonesia: "Kecerdasan Buatan Umum (AGI)" },
    { english: "Artificial Neural Network (ANN)", indonesia: "Jaringan Saraf Buatan (ANN)" },
    { english: "Association Rule Mining", indonesia: "Pertambangan Aturan Asosiasi" },
    { english: "Autonomous Systems", indonesia: "Sistem Otonom" },
    { english: "Backpropagation", indonesia: "Penyebaran Balik" },
    { english: "Batch Processing", indonesia: "Pengolahan Batch" },
    { english: "Bayesian Inference", indonesia: "Inferensi Bayesian" },
    { english: "Behavioral Analytics", indonesia: "Analitik Perilaku" },
    { english: "Big Data Analytics", indonesia: "Analitik Data Besar" },
    { english: "Binary Classification", indonesia: "Klasifikasi Biner" },
    { english: "Bioinformatics", indonesia: "Bioinformatika" },
    { english: "Blockchain Technology", indonesia: "Teknologi Blockchain" },
    { english: "Bots", indonesia: "Bot" },
    { english: "Business Intelligence (BI)", indonesia: "Intelijen Bisnis (BI)" },
    { english: "Chatbot", indonesia: "Bot Obrolan" },
    { english: "Classification", indonesia: "Klasifikasi" },
    { english: "Clickstream Analysis", indonesia: "Analisis Aliran Klik" },
    { english: "Cloud Computing", indonesia: "Komputasi Awan" },
    { english: "Cluster Analysis", indonesia: "Analisis Klaster" },
    { english: "CNN (Convolutional Neural Network)", indonesia: "Jaringan Saraf Konvolusional (CNN)" },
    { english: "Collaborative Filtering", indonesia: "Penyaringan Kolaboratif" },
    { english: "Computational Biology", indonesia: "Biologi Komputasional" },
    { english: "Computer Vision", indonesia: "Visi Komputer" },
    { english: "Content Management System (CMS)", indonesia: "Sistem Manajemen Konten (CMS)" },
    { english: "Convolution", indonesia: "Konvolusi" },
    { english: "Cybersecurity", indonesia: "Keamanan Siber" },
    { english: "Data Aggregation", indonesia: "Agregasi Data" },
    { english: "Data Analytics", indonesia: "Analitik Data" },
    { english: "Data Cleaning", indonesia: "Pembersihan Data" },
    { english: "Data Compression", indonesia: "Kompresi Data" },
    { english: "Data Engineering", indonesia: "Rekayasa Data" },
    { english: "Data Governance", indonesia: "Tata Kelola Data" },
    { english: "Data Integration", indonesia: "Integrasi Data" },
    { english: "Data Lake", indonesia: "Danau Data" },
    { english: "Data Leakage", indonesia: "Kebocoran Data" },
    { english: "Data Loss Prevention (DLP)", indonesia: "Pencegahan Kehilangan Data (DLP)" },
    { english: "Data Management", indonesia: "Manajemen Data" },
    { english: "Data Mining", indonesia: "Pertambangan Data" },
    { english: "Data Modeling", indonesia: "Pemodelan Data" },
    { english: "Data Preprocessing", indonesia: "Pra-Pemrosesan Data" },
    { english: "Data Privacy", indonesia: "Privasi Data" },
    { english: "Data Protection", indonesia: "Perlindungan Data" },
    { english: "Data Quality", indonesia: "Kualitas Data" },
    { english: "Data Science", indonesia: "Ilmu Data" },
    { english: "Data Security", indonesia: "Keamanan Data" },
    { english: "Data Structures", indonesia: "Struktur Data" },
    { english: "Data Visualization", indonesia: "Visualisasi Data" },
    { english: "Database Management System (DBMS)", indonesia: "Sistem Manajemen Basis Data (DBMS)" },
    { english: "Decision Support System (DSS)", indonesia: "Sistem Pendukung Keputusan (DSS)" },
    { english: "Deep Learning", indonesia: "Pembelajaran Mendalam" },
    { english: "Deepfake", indonesia: "Palsu Mendalam" },
    { english: "Deepfake Detection", indonesia: "Deteksi Palsu Mendalam" },
    { english: "Defect Prediction", indonesia: "Prediksi Cacat" },
    { english: "Denial of Service (DoS)", indonesia: "Penolakan Layanan (DoS)" },
    { english: "Digital Forensics", indonesia: "Forensik Digital" },
    { english: "Dimensionality Reduction", indonesia: "Reduksi Dimensi" },
    { english: "Distributed Computing", indonesia: "Komputasi Terdistribusi" },
    { english: "Document Classification", indonesia: "Klasifikasi Dokumen" },
    { english: "Edge Computing", indonesia: "Komputasi Pinggiran" },
    { english: "EHR (Electronic Health Record)", indonesia: "Rekam Medis Elektronik (EHR)" },
    { english: "Emotion Recognition", indonesia: "Pengenalan Emosi" },
    { english: "Encryption", indonesia: "Enkripsi" },
    { english: "Ensemble Learning", indonesia: "Pembelajaran Ensemble" },
    { english: "Entity Resolution", indonesia: "Resolusi Entitas" },
    { english: "Epidemic Modeling", indonesia: "Pemodelan Epidemi" },
    { english: "Error Detection and Correction", indonesia: "Deteksi dan Koreksi Kesalahan" },
    { english: "Explainable AI (XAI)", indonesia: "Kecerdasan Buatan yang Dapat Diuraikan (XAI)" },
    { english: "Expert System", indonesia: "Sistem Pakar" },
    { english: "Facial Recognition", indonesia: "Pengenalan Wajah" },
    { english: "Federated Learning", indonesia: "Pembelajaran Terfederasi" },
    { english: "Feedback Loop", indonesia: "Loop Umpan Balik" },
    { english: "File System", indonesia: "Sistem Berkas" },
    { english: "Finite State Machine (FSM)", indonesia: "Mesin Keadaan Terbatas (FSM)" },
    { english: "Fraud Detection", indonesia: "Deteksi Penipuan" },
    { english: "Fuzzy Logic", indonesia: "Logika Fuzzy" },
    { english: "Game Theory", indonesia: "Teori Permainan" },
    { english: "GDPR (General Data Protection Regulation)", indonesia: "Peraturan Perlindungan Data Umum (GDPR)" },
    { english: "Geospatial Analysis", indonesia: "Analisis Geospasial" },
    { english: "Git (Version Control System)", indonesia: "Git (Sistem Kontrol Versi)" },
    { english: "GPU (Graphics Processing Unit)", indonesia: "GPU (Unit Pemrosesan Grafis)" },
    { english: "Graph Database", indonesia: "Basis Data Graf" },
    { english: "Hadoop", indonesia: "Hadoop" },
    { english: "Hash Function", indonesia: "Fungsi Hash" },
    { english: "Healthcare Informatics", indonesia: "Informatika Kesehatan" },
    { english: "Heuristic Algorithm", indonesia: "Algoritma Heuristik" },
    { english: "Hidden Markov Model (HMM)", indonesia: "Model Markov Tersembunyi (HMM)" },
    { english: "Human-Computer Interaction (HCI)", indonesia: "Interaksi Manusia-Komputer (HCI)" },
    { english: "Hybrid Model", indonesia: "Model Hibrida" },
    { english: "Hypothesis Testing", indonesia: "Pengujian Hipotesis" },
    { english: "Identity Verification", indonesia: "Verifikasi Identitas" },
    { english: "Image Processing", indonesia: "Pengolahan Citra" },
    { english: "Imposter Syndrome", indonesia: "Sindrom Pembohong" },
    { english: "Incremental Learning", indonesia: "Pembelajaran Bertahap" },
    { english: "Inductive Reasoning", indonesia: "Penalaran Induktif" },
    { english: "Information Retrieval", indonesia: "Pemulihan Informasi" },
    { english: "Internet of Things (IoT)", indonesia: "Internet of Things (IoT)" },
    { english: "Intrusion Detection System (IDS)", indonesia: "Sistem Deteksi Intrusi (IDS)" },
    { english: "Java (Programming Language)", indonesia: "Java (Bahasa Pemrograman)" },
    { english: "JavaScript (Programming Language)", indonesia: "JavaScript (Bahasa Pemrograman)" },
    { english: "K-means Clustering", indonesia: "Pengelompokan K-means" },
    { english: "Knowledge Graph", indonesia: "Graf Pengetahuan" },
    { english: "Lambda Architecture", indonesia: "Arsitektur Lambda" },
    { english: "LASSO (Least Absolute Shrinkage and Selection Operator)", indonesia: "LASSO (Operator Seleksi dan Penyusutan Absolut Terkecil)" },
    { english: "Latent Dirichlet Allocation (LDA)", indonesia: "Alokasi Dirichlet Tersembunyi (LDA)" },
    { english: "Latent Semantic Analysis (LSA)", indonesia: "Analisis Semantik Tersembunyi (LSA)" },
    { english: "Machine Learning", indonesia: "Pembelajaran Mesin" },
    { english: "MapReduce", indonesia: "MapReduce" },
    { english: "Market Basket Analysis", indonesia: "Analisis Keranjang Pasar" },
    { english: "Markov Chain", indonesia: "Rantai Markov" },
    { english: "Metadata", indonesia: "Metadata" },
    { english: "Microservices", indonesia: "Microservices" },
    { english: "Model Evaluation", indonesia: "Evaluasi Model" },
    { english: "Model Interpretability", indonesia: "Interpretabilitas Model" },
    { english: "Multiclass Classification", indonesia: "Klasifikasi Multikelas" },
    { english: "Multimodal Learning", indonesia: "Pembelajaran Multimodal" },
    { english: "Multivariate Analysis", indonesia: "Analisis Multivariat" },
    { english: "Natural Language Processing (NLP)", indonesia: "Pemrosesan Bahasa Alami (NLP)" },
    { english: "Neural Network Architecture", indonesia: "Arsitektur Jaringan Saraf" },
    { english: "NoSQL Database", indonesia: "Basis Data NoSQL" },
    { english: "Object Detection", indonesia: "Deteksi Objek" },
    { english: "Object-Oriented Programming (OOP)", indonesia: "Pemrograman Berorientasi Objek (OOP)" },
    { english: "OCR (Optical Character Recognition)", indonesia: "OCR (Pengenalan Karakter Optik)" },
    { english: "Online Learning", indonesia: "Pembelajaran Online" },
    { english: "Open Source", indonesia: "Sumber Terbuka" },
    { english: "Outlier Detection", indonesia: "Deteksi Pencilan" },
    { english: "Overfitting", indonesia: "Overfitting" },
    { english: "Parallel Computing", indonesia: "Komputasi Paralel" },
    { english: "Particle Swarm Optimization (PSO)", indonesia: "Optimisasi Awan Partikel (PSO)" },
    { english: "Pattern Recognition", indonesia: "Pengenalan Pola" },
    { english: "Peer Review", indonesia: "Tinjauan Rekan" },
    { english: "Performance Metrics", indonesia: "Metrik Kinerja" },
    { english: "Phishing", indonesia: "Phishing" },
    { english: "Predictive Analytics", indonesia: "Analitik Prediktif" },
    { english: "Privacy-Preserving Data Mining", indonesia: "Penambangan Data yang Memperhatikan Privasi" },
    { english: "Probabilistic Graphical Model", indonesia: "Model Grafik Probabilistik" },
    { english: "Programmatic Advertising", indonesia: "Periklanan Programatik" },
    { english: "Python (Programming Language)", indonesia: "Python (Bahasa Pemrograman)" },
    { english: "Q-learning", indonesia: "Pembelajaran Q" },
    { english: "Quantum Computing", indonesia: "Komputasi Kuantum" },
    { english: "R (Programming Language)", indonesia: "R (Bahasa Pemrograman)" },
    { english: "Random Forest", indonesia: "Hutan Acak" },
    { english: "Recommender System", indonesia: "Sistem Rekomendasi" },
    { english: "Regression Analysis", indonesia: "Analisis Regresi" },
    { english: "Reinforcement Learning", indonesia: "Pembelajaran Penguatan" },
    { english: "Remote Sensing", indonesia: "Pencitraan Jauh" },
    { english: "Reproducible Research", indonesia: "Penelitian yang Dapat Direproduksi" },
    { english: "Reverse Engineering", indonesia: "Rekayasa Balik" },
    { english: "Risk Assessment", indonesia: "Penilaian Risiko" },
    { english: "Robotics", indonesia: "Robotika" },
    { english: "Root Cause Analysis", indonesia: "Analisis Akar Penyebab" },
    { english: "Ruby (Programming Language)", indonesia: "Ruby (Bahasa Pemrograman)" },
    { english: "RPA (Robotic Process Automation)", indonesia: "Otomatisasi Proses Robotik (RPA)" },
    { english: "Rule-Based System", indonesia: "Sistem Berbasis Aturan" },
    { english: "SaaS (Software as a Service)", indonesia: "Perangkat Lunak sebagai Layanan (SaaS)" },
    { english: "Scala (Programming Language)", indonesia: "Scala (Bahasa Pemrograman)" },
    { english: "Scikit-learn", indonesia: "Scikit-learn" },
    { english: "Search Engine Optimization (SEO)", indonesia: "Optimisasi Mesin Pencari (SEO)" },
    { english: "Secure Multiparty Computation (SMC)", indonesia: "Komputasi Aman Multipihak (SMC)" },
    { english: "Security Token", indonesia: "Token Keamanan" },
    { english: "Sentiment Analysis", indonesia: "Analisis Sentimen" },
    { english: "Sequence Alignment", indonesia: "Penyelarasan Urutan" },
    { english: "Sequential Pattern Mining", indonesia: "Penambangan Pola Berurutan" },
    { english: "SIEM (Security Information and Event Management)", indonesia: "Manajemen Informasi dan Kejadian Keamanan (SIEM)" },
    { english: "Simulation", indonesia: "Simulasi" },
    { english: "Singular Value Decomposition (SVD)", indonesia: "Dekomposisi Nilai Tunggal (SVD)" },
    { english: "Smart Contract", indonesia: "Kontrak Pintar" },
    { english: "Social Network Analysis (SNA)", indonesia: "Analisis Jaringan Sosial (SNA)" },
    { english: "Software Engineering", indonesia: "Rekayasa Perangkat Lunak" },
    { english: "Software Testing", indonesia: "Pengujian Perangkat Lunak" },
    { english: "Source Code", indonesia: "Kode Sumber" },
    { english: "SQL (Structured Query Language)", indonesia: "SQL (Bahasa Permintaan Terstruktur)" },
    { english: "SSL/TLS (Secure Sockets Layer/Transport Layer Security)", indonesia: "SSL/TLS (Lapisan Soket Aman/Keamanan Lapisan Transport)" },
    { english: "Stochastic Gradient Descent (SGD)", indonesia: "Penurunan Gradien Stokastik (SGD)" },
    { english: "Supervised Learning", indonesia: "Pembelajaran Terawasi" },
    { english: "Support Vector Machine (SVM)", indonesia: "Mesin Vektor Pendukung (SVM)" },
    { english: "Swarm Intelligence", indonesia: "Kecerdasan Kelompok" },
    { english: "System Integration", indonesia: "Integrasi Sistem" },
    { english: "Tableau (Data Visualization Tool)", indonesia: "Tableau (Alat Visualisasi Data)" },
    { english: "TensorFlow", indonesia: "TensorFlow" },
    { english: "Text Analytics", indonesia: "Analitik Teks" },
    { english: "Threat Intelligence", indonesia: "Intelijen Ancaman" },
    { english: "Time Series Analysis", indonesia: "Analisis Seri Waktu" },
    { english: "Transfer Learning", indonesia: "Pembelajaran Transfer" },
    { english: "Trust Model", indonesia: "Model Kepercayaan" },
    { english: "UI/UX Design", indonesia: "Desain Antarmuka Pengguna (UI/UX)" },
    { english: "Unstructured Data", indonesia: "Data Tidak Terstruktur" },
    { english: "Usability Testing", indonesia: "Pengujian Kegunaan" },
    { english: "User Authentication", indonesia: "Otentikasi Pengguna" },
    { english: "User Interface", indonesia: "Antarmuka Pengguna" },
    { english: "Variational Autoencoder (VAE)", indonesia: "Autoencoder Variasional (VAE)" },
    { english: "Version Control", indonesia: "Kontrol Versi" },
    { english: "Virtual Private Network (VPN)", indonesia: "Jaringan Pribadi Virtual (VPN)" },
    { english: "Virtual Reality (VR)", indonesia: "Realitas Virtual (VR)" },
    { english: "Voice Recognition", indonesia: "Pengenalan Suara" },
    { english: "Web Analytics", indonesia: "Analitik Web" },
    { english: "Web Scraping", indonesia: "Penambangan Web" },
    { english: "Web Security", indonesia: "Keamanan Web" },
    { english: "Zero-Day Vulnerability", indonesia: "Kerentanan Nol Hari" }
};

// Function to populate the dictionary list
function populateDictionary() {
    var ul = document.getElementById('dictionaryList');
    ul.innerHTML = ''; // Clear previous content

    // Loop through the dictionary data and create list items
    dictionary.forEach(function(item) {
        var li = document.createElement('li');
        li.innerHTML = '<strong>' + item.english + '</strong> - ' + item.indonesian;
        ul.appendChild(li);
    });
}

// Call the function to populate the dictionary list initially
populateDictionary();

// Function to search the dictionary
function searchDictionary() {
    var input, filter, ul, li, strong, i, txtValue;
    input = document.getElementById('searchInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById('dictionaryList');
    li = ul.getElementsByTagName('li');

    for (i = 0; i < li.length; i++) {
        strong = li[i].getElementsByTagName('strong')[0];
        txtValue = strong.textContent || strong.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
